#!/bin/bash

# restart kded4, which will clear all the broken system tray icons.
# See http://forum.kde.org/viewtopic.php?f=67&t=99419&sid=ec78d6deb0f6beff6a60ba92a1f112b6&start=15
killall kded4
sleep 30s
kded4
