#!/bin/bash
#script for allowing Neo Freerunner/openmoko to access the 'net over usb (I think)

iptables -A POSTROUTING -t nat -j MASQUERADE -s 192.168.0.0/24 --out-interface wlan0
sysctl -w net.ipv4.ip_forward=1

scp /etc/resolv.conf root@192.168.0.202:/etc/

